"""
Multiscale clustering detector for SMLM data.

Adapted from the cosmic multiscale test (originally validated against ΛCDM
galaxy simulations). The statistical framework is unchanged: counts-in-cell
variance and skewness over a logarithmic range of scales, compared against
a null distribution using a covariance-aware χ² test with shrinkage
regularization.

Key differences from the cosmic version:

1. No periodic boundary conditions. Cells don't wrap around.
   CIC gridding uses hard boundaries (positions clipped to [0, grid_size-1]).

2. Scale range in nm, not Mpc/h grid units. The detector converts between
   physical nm and grid units given the physical size of the ROI.

3. The null model is the biological CSR (convex hull), not a rectangular box.
   Null curves are generated by the caller and passed in.

4. Anisotropy-aware: the grid can have different voxel sizes in z to account
   for the worse axial localization precision. But by default we use an
   isotropic grid and simply let the scale range cover the relevant physical
   scales.

Usage pattern:

    # 1. Blink-correct your data
    corrector = BlinkingCorrector(r_lateral=30, r_axial=60, max_dark_frames=5)
    result = corrector.correct(raw_positions, frames, photons)

    # 2. Build null model from corrected data
    null = BiologicalNullModel(seed=42)
    null.fit(result.positions)
    mock_positions = null.generate_mocks(n_points=len(result.positions), n_mocks=50)

    # 3. Run multiscale test
    detector = SMLMMultiscaleTest.from_positions(result.positions)
    scale_range = ScaleRange.for_smlm(min_nm=20, max_nm=500, n_scales=12)
    results = detector.test(result.positions, mock_positions, scale_range)
"""

import numpy as np
from scipy import stats
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class DatasetInfo:
    """
    Enforce parameter matching between datasets.

    Box size mismatch is the most common source of spurious chi-squared
    anomalies -- learned from the cosmic version of this code where a
    75 vs 100 Mpc/h mismatch gave chi^2 ~ 350,000.
    """
    n_points: int
    roi_size_nm: np.ndarray   # (3,) physical ROI dimensions in nm [x, y, z]
    grid_size: int

    def matches(self, other: 'DatasetInfo', tol: float = 0.05) -> tuple:
        if abs(self.n_points - other.n_points) / max(self.n_points, 1) > tol:
            return False, f"N mismatch: {self.n_points} vs {other.n_points}"
        roi_rel = np.abs(self.roi_size_nm - other.roi_size_nm) / np.maximum(self.roi_size_nm, 1)
        if (roi_rel > tol).any():
            return False, f"ROI mismatch: {self.roi_size_nm} vs {other.roi_size_nm}"
        if self.grid_size != other.grid_size:
            return False, f"Grid mismatch: {self.grid_size} vs {other.grid_size}"
        return True, "Match"


@dataclass
class ScaleRange:
    """
    Physical scale range for the multiscale test.

    Stores scales in both nm (physical) and grid voxels. Grid voxels are
    what the CIC + counting functions operate on.
    """
    cell_sizes_vox: List[int]   # in grid voxels
    cell_sizes_nm: List[float]  # corresponding physical sizes in nm

    @classmethod
    def for_smlm(cls, min_nm: float = 20.0, max_nm: float = 500.0,
                 n_scales: int = 12,
                 roi_size_nm: float = 5000.0,
                 grid_size: int = 64) -> 'ScaleRange':
        """
        Build a logarithmic scale range appropriate for SMLM.

        Parameters
        ----------
        min_nm : float
            Minimum cell size in nm. Should be >= localization precision (~20 nm).
        max_nm : float
            Maximum cell size in nm. Should be <= ROI size / 4.
        n_scales : int
            Number of logarithmic steps.
        roi_size_nm : float
            Physical size of the largest ROI dimension in nm.
            Used to convert nm -> grid voxels.
        grid_size : int
            Grid dimension (grid is grid_size^3 voxels).
        """
        nm_per_vox = roi_size_nm / grid_size
        sizes_nm = np.logspace(np.log10(min_nm), np.log10(max_nm), n_scales)
        sizes_vox = np.maximum(1, (sizes_nm / nm_per_vox).astype(int))
        sizes_vox = np.unique(sizes_vox)  # remove duplicates from rounding
        sizes_nm_actual = sizes_vox * nm_per_vox

        return cls(
            cell_sizes_vox=sizes_vox.tolist(),
            cell_sizes_nm=sizes_nm_actual.tolist()
        )

    @classmethod
    def logarithmic(cls, min_vox: int = 3, max_vox: int = 32,
                    n_scales: int = 12) -> 'ScaleRange':
        """
        Logarithmic range in grid units (mirrors the cosmic API for compatibility).
        """
        sizes = np.logspace(np.log10(min_vox), np.log10(max_vox), n_scales)
        sizes = np.unique(sizes.astype(int))
        nm_placeholder = [float(s) for s in sizes]
        return cls(cell_sizes_vox=sizes.tolist(), cell_sizes_nm=nm_placeholder)


class SMLMMultiscaleTest:
    """
    Multiscale clustering test adapted for SMLM point cloud data.

    The test measures clustering at multiple spatial scales by computing
    variance and skewness of counts-in-cells over a logarithmic scale range.
    These statistics are compared against a biological null distribution
    using a covariance-aware chi^2 statistic.

    Parameters
    ----------
    roi_size_nm : ndarray, shape (3,)
        Physical ROI dimensions [x, y, z] in nm. Positions will be normalized
        to this range before gridding.
    grid_size : int
        Number of voxels per side. 64 is appropriate for most SMLM datasets
        (balances scale resolution against computation time).
    """

    def __init__(self, roi_size_nm: np.ndarray, grid_size: int = 64):
        self.roi_size_nm = np.asarray(roi_size_nm, dtype=float)
        self.grid_size = grid_size

    @classmethod
    def from_positions(cls, positions: np.ndarray,
                       grid_size: int = 64) -> 'SMLMMultiscaleTest':
        """
        Build a detector whose ROI is inferred from the data bounds.
        This is the typical usage pattern.
        """
        positions = np.asarray(positions, dtype=float)
        roi_size = positions.max(axis=0) - positions.min(axis=0)
        # Pad by 1% to avoid boundary issues
        roi_size = roi_size * 1.01
        return cls(roi_size_nm=roi_size, grid_size=grid_size)

    def grid_positions(self, positions: np.ndarray) -> np.ndarray:
        """
        Cloud-in-Cell (CIC) density field on a 3D grid.

        Positions are first normalized to [0, grid_size - 1], then each
        point distributes its weight to the 8 surrounding voxels using
        trilinear interpolation. No periodic wrapping (SMLM data is not
        a periodic domain).

        Parameters
        ----------
        positions : ndarray, shape (N, 3)
            Localization positions in nm.

        Returns
        -------
        grid : ndarray, shape (G, G, G)
            Density field. Sum equals len(positions).
        """
        positions = np.asarray(positions, dtype=float)
        mins = positions.min(axis=0)
        maxs = positions.max(axis=0)
        span = maxs - mins

        # Handle degenerate dimensions (all points at same z, e.g. 2D data)
        span = np.where(span == 0, 1.0, span)

        pos_norm = (positions - mins) / span * (self.grid_size - 1)
        pos_norm = np.clip(pos_norm, 0, self.grid_size - 1 - 1e-9)

        grid = np.zeros((self.grid_size,) * 3, dtype=float)

        for pos in pos_norm:
            i, j, k = pos.astype(int)
            dx, dy, dz = pos[0] - i, pos[1] - j, pos[2] - k

            for di in range(2):
                ii = min(i + di, self.grid_size - 1)
                wx = (1 - dx) if di == 0 else dx
                for dj in range(2):
                    jj = min(j + dj, self.grid_size - 1)
                    wy = (1 - dy) if dj == 0 else dy
                    for dk in range(2):
                        kk = min(k + dk, self.grid_size - 1)
                        wz = (1 - dz) if dk == 0 else dz
                        grid[ii, jj, kk] += wx * wy * wz

        return grid

    def _bin_counts(self, grid: np.ndarray, cell_size: int) -> Optional[np.ndarray]:
        """
        Sum the density grid into non-overlapping cells of given voxel size.

        Returns None if cell_size > grid_size // 2 (too few cells).
        """
        if cell_size > self.grid_size // 2:
            return None

        counts = []
        g = self.grid_size
        for i in range(0, g - cell_size, cell_size):
            for j in range(0, g - cell_size, cell_size):
                for k in range(0, g - cell_size, cell_size):
                    counts.append(
                        grid[i:i+cell_size, j:j+cell_size, k:k+cell_size].sum()
                    )

        return np.array(counts) if len(counts) >= 4 else None

    def variance_at_scale(self, grid: np.ndarray, cell_size: int) -> float:
        """
        Counts variance-to-mean ratio (index of dispersion) at a given cell size.

        Returns np.nan if insufficient cells.
        """
        counts = self._bin_counts(grid, cell_size)
        if counts is None:
            return np.nan
        mean = counts.mean()
        return counts.var() / mean if mean > 0 else np.nan

    def skewness_at_scale(self, grid: np.ndarray, cell_size: int) -> float:
        """
        Counts skewness at a given cell size.

        Returns np.nan if insufficient cells or zero variance.
        """
        counts = self._bin_counts(grid, cell_size)
        if counts is None or counts.std() == 0:
            return np.nan
        return float(stats.skew(counts))

    def compute_curves(self, positions: np.ndarray,
                       scale_range: ScaleRange) -> dict:
        """
        Compute variance and skewness curves over all scales.

        Parameters
        ----------
        positions : ndarray, shape (N, 3)
        scale_range : ScaleRange

        Returns
        -------
        dict with keys 'variance' and 'skewness', each a dict with
        'scales' (in voxels), 'scales_nm', and 'values'.
        """
        grid = self.grid_positions(positions)

        curves = {
            'variance': {'scales': [], 'scales_nm': [], 'values': []},
            'skewness': {'scales': [], 'scales_nm': [], 'values': []}
        }

        for vox, nm in zip(scale_range.cell_sizes_vox, scale_range.cell_sizes_nm):
            var = self.variance_at_scale(grid, vox)
            skew = self.skewness_at_scale(grid, vox)

            if not np.isnan(var):
                curves['variance']['scales'].append(vox)
                curves['variance']['scales_nm'].append(nm)
                curves['variance']['values'].append(var)

            if not np.isnan(skew):
                curves['skewness']['scales'].append(vox)
                curves['skewness']['scales_nm'].append(nm)
                curves['skewness']['values'].append(skew)

        return curves

    def chi_squared_with_covariance(self, real_curve: dict,
                                    mock_curves: list,
                                    shrinkage: float = 0.1) -> dict:
        """
        Covariance-aware chi^2 test.

        Measures how far the real data's multiscale curve deviates from the
        null distribution. The covariance matrix accounts for correlation
        between scales. Ledoit-Wolf style shrinkage regularization stabilizes
        matrix inversion when the number of mocks is small relative to scales.

        The shrinkage parameter lambda=0.1 keeps the condition number around
        10^3 for typical inputs (5-50 mocks, 8-12 valid scales).

        Parameters
        ----------
        real_curve : dict
            Output of compute_curves() for a single metric (e.g. 'variance').
        mock_curves : list of dict
            Output of compute_curves() for each mock dataset, same metric.
        shrinkage : float
            Regularization strength in [0, 1]. 0 = no regularization,
            1 = diagonal covariance.

        Returns
        -------
        dict with chi_squared, dof, p_value, condition_number, n_mocks_used
        """
        real_vals = np.array(real_curve['values'])
        n_scales = len(real_vals)

        mock_matrix = []
        for mc in mock_curves:
            mv = np.array(mc['values'])
            if len(mv) == n_scales:
                mock_matrix.append(mv)

        n_mocks = len(mock_matrix)
        if n_mocks < 2:
            return {
                'chi_squared': 0.0,
                'dof': n_scales,
                'p_value': 1.0,
                'condition_number': np.inf,
                'n_mocks_used': n_mocks
            }

        mock_matrix = np.array(mock_matrix)  # (n_mocks, n_scales)
        mock_mean = mock_matrix.mean(axis=0)
        mock_cov = np.cov(mock_matrix.T)

        if mock_cov.ndim == 0:
            # Only one scale -- scalar case
            mock_cov = np.atleast_2d(mock_cov)

        # Ledoit-Wolf style shrinkage toward diagonal
        diag_cov = np.diag(np.diag(mock_cov))
        mock_cov_reg = (1 - shrinkage) * mock_cov + shrinkage * diag_cov
        # Small ridge for numerical stability
        mock_cov_reg += np.eye(n_scales) * 1e-10

        residual = real_vals - mock_mean

        try:
            cov_inv = np.linalg.inv(mock_cov_reg)
            chi_sq = float(residual @ cov_inv @ residual)
            cond = float(np.linalg.cond(mock_cov_reg))
        except np.linalg.LinAlgError:
            # Fallback: diagonal-only
            var_diag = np.diag(mock_cov) + 1e-10
            chi_sq = float((residual**2 / var_diag).sum())
            cond = np.inf

        dof = n_scales
        p_value = float(1 - stats.chi2.cdf(chi_sq, dof))

        return {
            'chi_squared': chi_sq,
            'dof': dof,
            'p_value': p_value,
            'condition_number': cond,
            'n_mocks_used': n_mocks
        }

    def test(self, real_positions: np.ndarray,
             mock_positions_list: list,
             scale_range: ScaleRange,
             shrinkage: float = 0.1) -> dict:
        """
        Run the full multiscale test: real data vs. null mocks.

        Parameters
        ----------
        real_positions : ndarray, shape (N, 3)
            Blinking-corrected localization positions in nm.
        mock_positions_list : list of ndarray
            CSR null mock datasets, each shape (N, 3).
        scale_range : ScaleRange
        shrinkage : float

        Returns
        -------
        dict with keys 'variance' and 'skewness', each containing the
        chi_squared result dict plus the real and mock curves.
        """
        real_curves = self.compute_curves(real_positions, scale_range)

        mock_curves_by_metric = {'variance': [], 'skewness': []}
        for mock_pos in mock_positions_list:
            mc = self.compute_curves(mock_pos, scale_range)
            for metric in ['variance', 'skewness']:
                mock_curves_by_metric[metric].append(mc[metric])

        results = {}
        for metric in ['variance', 'skewness']:
            chi2_result = self.chi_squared_with_covariance(
                real_curves[metric],
                mock_curves_by_metric[metric],
                shrinkage=shrinkage
            )
            results[metric] = {
                **chi2_result,
                'real_curve': real_curves[metric],
                'mock_curves': mock_curves_by_metric[metric]
            }

        return results
